# 一、ndarray
## 1. ndarray特性
### 多维性

In [2]:
import numpy as np

In [3]:
arr = np.array(5)
print(arr)
print('维度', arr.ndim)

5
维度 0


In [4]:
arr = np.array([1, 2, 3])
print(arr)
print('维度', arr.ndim)

[1 2 3]
维度 1


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('维度', arr.ndim)

[[1 2 3]
 [4 5 6]]
维度 2


### 同质性

In [6]:
arr = np.array([1, 'hello'])
print(arr)
# 1 是int，但因为有同质性，所以int转为字符串
# 不同的数据类型会强制转换为相同数据类型

['1' 'hello']


In [7]:
arr = np.array([1, 2.5])
print(arr)


[1.  2.5]


## 2. ndarray属性

In [22]:
arr = np.array(1)
print(arr)
print('数组性状', arr.shape) # 数组性状
print('数组维度', arr.ndim)
print('元素个数', arr.size)
print('数据类型', arr.dtype)
print('元素的转制', arr.T)

1
数组性状 ()
数组维度 0
元素个数 1
数据类型 int64
元素的转制 1


In [23]:
arr = np.array([1, 2.4, 3])
print(arr)
print('数组性状',arr.shape) # 数组性状
print('数组唯独', arr.ndim)
print('元素个数', arr.size)
print('数据类型', arr.dtype)
print('元素的转制', arr.T)

[1.  2.4 3. ]
数组性状 (3,)
数组唯独 1
元素个数 3
数据类型 float64
元素的转制 [1.  2.4 3. ]


In [25]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print('数组性状', arr.shape) # 数组性状
print('数组维度', arr.ndim)
print('元素个数', arr.size)
print('数据类型', arr.dtype)
print('元素的转制', arr.T) # 二维的才有用 

[[1 2 3]
 [4 5 6]]
数组性状 (2, 3)
数组维度 2
元素个数 6
数据类型 int64
元素的转制 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarry创建

In [27]:
# 基础创建方法
list1 = [4, 5, 6]
arr = np.array(list1, float) # 数据，dtype
print(arr.ndim) # 属性后不带括号，带括号是命令、方法
print(arr)

1
[4. 5. 6.]


In [30]:
# copy
arr1 = np.copy(arr) # arr1元素跟原始数组相同，但不是一个数组
print(arr1)
arr1[0] = 8
print(arr1)

[4. 5. 6.]
[8. 5. 6.]


### 预定义形状

全0 全1 未初始化 固定值

#### 全0


In [34]:
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [39]:
arr = np.zeros((3, ), dtype=int)
print(arr)

[0 0 0]


#### 全1

In [40]:
arr = np.ones((5, 8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


#### 未初始化

In [46]:
arr = np.empty((2, 8)) # 比ones更快，不太推荐
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 填充

In [50]:
arr = np.full((5, 7), 57)
print(arr)

[[57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57]
 [57 57 57 57 57 57 57]]


#### like

In [54]:
arr1 = np.zeros_like(arr) # 和arr的形状一样
print('zeros_like:', arr1)
arr2 = np.empty_like(arr) # 和arr的形状一样
print('empty_like:', arr2)
arr3 = np.full_like(arr, 99) # 和arr的形状一样
print('full_like:', arr3)

zeros_like: [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
empty_like: [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
full_like: [[99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]]


In [55]:
#### 等差数列

In [60]:
arr = np.arange(2, 11, 2) # start, end, step
print(arr)

[ 2  4  6  8 10]


In [61]:
#### 等间隔数列

In [65]:
arr = np.linspace(0, 10, 3) # start, end, num
print(arr)

[ 0.  5. 10.]


In [67]:
arr = np.linspace(0, 100, 5, dtype=int) # start, end, num
print(arr)
arr_r = np.arange(0, 101, 25)
print(arr_r)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [68]:
# 对数间隔数列

In [69]:
arr = np.logspace(0, 4, 3, base=2)
print(arr)

[ 1.  4. 16.]


In [70]:
arr = np.linspace(0, 4, 3)
print(arr)


[0. 2. 4.]
